import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, Bot, ChartNoAxesCombined, Coins, Gauge, Network, Waves, Zap } from "lucide-react";
import { LabShell } from "@/components/lab/lab-shell";
import { BitcoinNetworkActivityPanel } from "@/components/lab/bitcoin-network-activity-panel";
import { OnchainIntelligencePanel } from "@/components/lab/onchain-intelligence-panel";
import { WhaleFlowPanel } from "@/components/lab/whale-flow-panel";
import { ExchangeFlowPanel } from "@/components/lab/exchange-flow-panel";
import { MiningRevenuePanel } from "@/components/lab/mining-revenue-panel";
import { BtcMarketNetworkPanel } from "@/components/lab/btc-market-network-panel";
import { NetworkHealthPanel } from "@/components/lab/network-health-panel";
import { AiBlockchainAnalystPanel } from "@/components/lab/ai-blockchain-analyst-panel";
export const Route=createFileRoute("/lab/crypto-intelligence")({head:()=>({meta:[{title:"Crypto Intelligence — Quantum AI Lab"},{name:"description",content:"Independent crypto research workspace for Bitcoin network activity, on-chain intelligence, whale-flow monitoring, exchange-flow research, mining revenue, market/network charts, transparent health scoring and automated evidence-based analysis."},{property:"og:title",content:"Crypto Intelligence — Quantum AI Lab"},{property:"og:type",content:"website"}]}),component:Page});
const modules=[{icon:Activity,title:"Bitcoin Network Activity",text:"Mempool, transaction fees, block production and network throughput.",status:"LIVE",href:"#network-activity"},{icon:Network,title:"On-chain Intelligence",text:"Public-chain transaction, block and Lightning signals with source transparency.",status:"LIVE",href:"#on-chain"},{icon:Waves,title:"Whale Flow Monitor",text:"Large Bitcoin transfer detection from live public mempool data, with transparent methodology.",status:"LIVE",href:"#whale-flow"},{icon:Zap,title:"Bitcoin Fee & Mempool Intelligence",text:"Live fee pressure, confirmation tiers and unconfirmed transaction activity.",status:"LIVE",href:"#fee-intelligence"},{icon:Coins,title:"Mining Revenue Dashboard",text:"Block subsidy, fee revenue and miner-economics research from recent blocks.",status:"LIVE",href:"#mining-revenue"},{icon:ChartNoAxesCombined,title:"BTC Market + Network",text:"Interactive Bitcoin price and network hashrate research.",status:"LIVE",href:"#market-network"},{icon:Gauge,title:"Network Health Score",text:"Explainable component score built from measurable Bitcoin network signals.",status:"LIVE",href:"#health-score"},{icon:Bot,title:"AI Blockchain Analyst",text:"Evidence-linked automated summaries generated from live Bitcoin research feeds.",status:"LIVE",href:"#ai-analyst"}];
function Page(){return <LabShell crumb="Crypto Intelligence"><div className="mb-8 max-w-4xl"><span className="font-mono text-xs text-primary">RESEARCH / CRYPTO INTELLIGENCE</span><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Crypto Intelligence</h1><p className="mt-3 text-sm leading-7 text-muted-foreground">A dedicated research workspace for Bitcoin network, on-chain, whale-flow, fee, mempool and market intelligence. This is separate from the interactive Blockchain Research Lab so each workspace stays focused.</p><Link to="/lab/blockchain" className="mt-4 inline-flex rounded-sm border border-border px-3 py-2 font-mono text-[11px] uppercase text-muted-foreground hover:border-primary/60 hover:text-primary">Open Blockchain Research Lab →</Link></div><section className="rounded-md border border-border bg-card p-4 sm:p-5"><div className="font-mono text-[10px] uppercase tracking-wider text-primary">Research architecture</div><h2 className="mt-1 text-xl font-semibold">Eight intelligence modules</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{modules.map(({icon:Icon,title,text,status,href})=><a key={title} href={href} className="group rounded-md border border-border bg-background p-4 transition hover:border-primary/60 hover:bg-signal-soft"><div className="flex items-start justify-between gap-3"><Icon className="size-5 text-primary"/><span className="font-mono text-[9px] uppercase tracking-wider text-primary">{status}</span></div><h3 className="mt-4 font-semibold group-hover:text-primary">{title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{text}</p><div className="mt-3 font-mono text-[10px] uppercase text-primary">Open module ↓</div></a>)}</div></section><div className="my-4 rounded-md border border-primary/30 bg-signal-soft p-4 text-xs leading-6 text-muted-foreground"><span className="font-mono text-primary">RESEARCH STACK:</span> Eight modules are present. Live values are shown only when backed by a real public or verified data source.</div><BitcoinNetworkActivityPanel/><OnchainIntelligencePanel/><WhaleFlowPanel/><ExchangeFlowPanel/><MiningRevenuePanel/><BtcMarketNetworkPanel/><NetworkHealthPanel/><AiBlockchainAnalystPanel/></LabShell>}
