/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabArenaRouteImport } from './routes/lab.arena'
import { Route as LabAssistantRouteImport } from './routes/lab.assistant'
import { Route as LabCircuitBuilderRouteImport } from './routes/lab.circuit-builder'
import { Route as LabEntanglementRouteImport } from './routes/lab.entanglement'
import { Route as LabFinanceRouteImport } from './routes/lab.finance'
import { Route as LabIbmRouteImport } from './routes/lab.ibm'
import { Route as LabPortfolioRouteImport } from './routes/lab.portfolio'
import { Route as LabQaoaRouteImport } from './routes/lab.qaoa'
import { Route as LabQmlRouteImport } from './routes/lab.qml'
import { Route as LabReportsRouteImport } from './routes/lab.reports'
import { Route as LabVqeRouteImport } from './routes/lab.vqe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabArenaRoute = LabArenaRouteImport.update({
  id: '/lab/arena',
  path: '/lab/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAssistantRoute = LabAssistantRouteImport.update({
  id: '/lab/assistant',
  path: '/lab/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCircuitBuilderRoute = LabCircuitBuilderRouteImport.update({
  id: '/lab/circuit-builder',
  path: '/lab/circuit-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LabEntanglementRoute = LabEntanglementRouteImport.update({
  id: '/lab/entanglement',
  path: '/lab/entanglement',
  getParentRoute: () => rootRouteImport,
} as any)
const LabFinanceRoute = LabFinanceRouteImport.update({
  id: '/lab/finance',
  path: '/lab/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIbmRoute = LabIbmRouteImport.update({
  id: '/lab/ibm',
  path: '/lab/ibm',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPortfolioRoute = LabPortfolioRouteImport.update({
  id: '/lab/portfolio',
  path: '/lab/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LabQaoaRoute = LabQaoaRouteImport.update({
  id: '/lab/qaoa',
  path: '/lab/qaoa',
  getParentRoute: () => rootRouteImport,
} as any)
const LabQmlRoute = LabQmlRouteImport.update({
  id: '/lab/qml',
  path: '/lab/qml',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReportsRoute = LabReportsRouteImport.update({
  id: '/lab/reports',
  path: '/lab/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LabVqeRoute = LabVqeRouteImport.update({
  id: '/lab/vqe',
  path: '/lab/vqe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/assistant': typeof LabAssistantRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab/entanglement': typeof LabEntanglementRoute
  '/lab/finance': typeof LabFinanceRoute
  '/lab/ibm': typeof LabIbmRoute
  '/lab/portfolio': typeof LabPortfolioRoute
  '/lab/qaoa': typeof LabQaoaRoute
  '/lab/qml': typeof LabQmlRoute
  '/lab/reports': typeof LabReportsRoute
  '/lab/vqe': typeof LabVqeRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/assistant': typeof LabAssistantRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab/entanglement': typeof LabEntanglementRoute
  '/lab/finance': typeof LabFinanceRoute
  '/lab/ibm': typeof LabIbmRoute
  '/lab/portfolio': typeof LabPortfolioRoute
  '/lab/qaoa': typeof LabQaoaRoute
  '/lab/qml': typeof LabQmlRoute
  '/lab/reports': typeof LabReportsRoute
  '/lab/vqe': typeof LabVqeRoute
  '/lab': typeof LabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/assistant': typeof LabAssistantRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab/entanglement': typeof LabEntanglementRoute
  '/lab/finance': typeof LabFinanceRoute
  '/lab/ibm': typeof LabIbmRoute
  '/lab/portfolio': typeof LabPortfolioRoute
  '/lab/qaoa': typeof LabQaoaRoute
  '/lab/qml': typeof LabQmlRoute
  '/lab/reports': typeof LabReportsRoute
  '/lab/vqe': typeof LabVqeRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab/arena'
    | '/lab/assistant'
    | '/lab/circuit-builder'
    | '/lab/entanglement'
    | '/lab/finance'
    | '/lab/ibm'
    | '/lab/portfolio'
    | '/lab/qaoa'
    | '/lab/qml'
    | '/lab/reports'
    | '/lab/vqe'
    | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab/arena'
    | '/lab/assistant'
    | '/lab/circuit-builder'
    | '/lab/entanglement'
    | '/lab/finance'
    | '/lab/ibm'
    | '/lab/portfolio'
    | '/lab/qaoa'
    | '/lab/qml'
    | '/lab/reports'
    | '/lab/vqe'
    | '/lab'
  id:
    | '__root__'
    | '/'
    | '/lab/arena'
    | '/lab/assistant'
    | '/lab/circuit-builder'
    | '/lab/entanglement'
    | '/lab/finance'
    | '/lab/ibm'
    | '/lab/portfolio'
    | '/lab/qaoa'
    | '/lab/qml'
    | '/lab/reports'
    | '/lab/vqe'
    | '/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabArenaRoute: typeof LabArenaRoute
  LabAssistantRoute: typeof LabAssistantRoute
  LabCircuitBuilderRoute: typeof LabCircuitBuilderRoute
  LabEntanglementRoute: typeof LabEntanglementRoute
  LabFinanceRoute: typeof LabFinanceRoute
  LabIbmRoute: typeof LabIbmRoute
  LabPortfolioRoute: typeof LabPortfolioRoute
  LabQaoaRoute: typeof LabQaoaRoute
  LabQmlRoute: typeof LabQmlRoute
  LabReportsRoute: typeof LabReportsRoute
  LabVqeRoute: typeof LabVqeRoute
  LabIndexRoute: typeof LabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/arena': {
      id: '/lab/arena'
      path: '/lab/arena'
      fullPath: '/lab/arena'
      preLoaderRoute: typeof LabArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/assistant': {
      id: '/lab/assistant'
      path: '/lab/assistant'
      fullPath: '/lab/assistant'
      preLoaderRoute: typeof LabAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/circuit-builder': {
      id: '/lab/circuit-builder'
      path: '/lab/circuit-builder'
      fullPath: '/lab/circuit-builder'
      preLoaderRoute: typeof LabCircuitBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/entanglement': {
      id: '/lab/entanglement'
      path: '/lab/entanglement'
      fullPath: '/lab/entanglement'
      preLoaderRoute: typeof LabEntanglementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/finance': {
      id: '/lab/finance'
      path: '/lab/finance'
      fullPath: '/lab/finance'
      preLoaderRoute: typeof LabFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/ibm': {
      id: '/lab/ibm'
      path: '/lab/ibm'
      fullPath: '/lab/ibm'
      preLoaderRoute: typeof LabIbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/portfolio': {
      id: '/lab/portfolio'
      path: '/lab/portfolio'
      fullPath: '/lab/portfolio'
      preLoaderRoute: typeof LabPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/qaoa': {
      id: '/lab/qaoa'
      path: '/lab/qaoa'
      fullPath: '/lab/qaoa'
      preLoaderRoute: typeof LabQaoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/qml': {
      id: '/lab/qml'
      path: '/lab/qml'
      fullPath: '/lab/qml'
      preLoaderRoute: typeof LabQmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/reports': {
      id: '/lab/reports'
      path: '/lab/reports'
      fullPath: '/lab/reports'
      preLoaderRoute: typeof LabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/vqe': {
      id: '/lab/vqe'
      path: '/lab/vqe'
      fullPath: '/lab/vqe'
      preLoaderRoute: typeof LabVqeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabArenaRoute: LabArenaRoute,
  LabAssistantRoute: LabAssistantRoute,
  LabCircuitBuilderRoute: LabCircuitBuilderRoute,
  LabEntanglementRoute: LabEntanglementRoute,
  LabFinanceRoute: LabFinanceRoute,
  LabIbmRoute: LabIbmRoute,
  LabPortfolioRoute: LabPortfolioRoute,
  LabQaoaRoute: LabQaoaRoute,
  LabQmlRoute: LabQmlRoute,
  LabReportsRoute: LabReportsRoute,
  LabVqeRoute: LabVqeRoute,
  LabIndexRoute: LabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
