/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabArenaRouteImport } from './routes/lab.arena'
import { Route as LabCircuitBuilderRouteImport } from './routes/lab.circuit-builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabArenaRoute = LabArenaRouteImport.update({
  id: '/lab/arena',
  path: '/lab/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCircuitBuilderRoute = LabCircuitBuilderRouteImport.update({
  id: '/lab/circuit-builder',
  path: '/lab/circuit-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab': typeof LabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab/arena': typeof LabArenaRoute
  '/lab/circuit-builder': typeof LabCircuitBuilderRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lab/arena' | '/lab/circuit-builder' | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab/arena' | '/lab/circuit-builder' | '/lab'
  id: '__root__' | '/' | '/lab/arena' | '/lab/circuit-builder' | '/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabArenaRoute: typeof LabArenaRoute
  LabCircuitBuilderRoute: typeof LabCircuitBuilderRoute
  LabIndexRoute: typeof LabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/arena': {
      id: '/lab/arena'
      path: '/lab/arena'
      fullPath: '/lab/arena'
      preLoaderRoute: typeof LabArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/circuit-builder': {
      id: '/lab/circuit-builder'
      path: '/lab/circuit-builder'
      fullPath: '/lab/circuit-builder'
      preLoaderRoute: typeof LabCircuitBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabArenaRoute: LabArenaRoute,
  LabCircuitBuilderRoute: LabCircuitBuilderRoute,
  LabIndexRoute: LabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
